version: '3'
services:
  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2
    networks:
      - verticaspark
    container_name: spark-master
    volumes:
      - ./spark_jobs:/opt/hadoopspark
    ports:
      - "8080:8080"
      - "7077:7077"
  spark-worker-1:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    networks:
      - verticaspark
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
  spark-worker-2:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    networks:
      - verticaspark
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
  vertica:
    image: jbfavre/vertica
    container_name: vertica_db
    networks:
      - verticaspark
    volumes:
      - ./input/:/tmp/input
    ports:
      - 5433:5433
networks:
  verticaspark:
    external: true